[package]
name = "flint"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "Flint — local AI for the rest of us"

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "flint_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
common = { workspace = true }
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = "1"
tokio = { version = "1", features = ["process", "time", "sync", "io-util", "rt-multi-thread"] }
